name: keygen

on:
  issues:
    types: [opened,edited]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/github-script@v6
      with:
        script: |
          const script = require('./scripts/keygen.js')
          const crypto = require('crypto')
          await script({github, context, crypto, PRIVATE_KEY:`${{secrets.PRIVATE_KEY}}`})
